export const ADD_FAVORITE = 'ADD_FAVORITE'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'

export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE'
export const REMOVE_RROM_FAVORITE = 'REMOVE_RROM_FAVORITE'