export const SET_FAVORITE_CITY = 'SET_FAVORITE_CITY'
export const RESET_FAVORITE_CITY = 'RESET_FAVORITE_CITY'

export const SET_FAVORITE_SAGA_CITY = 'SET_FAVORITE_SAGA_CITY'
export const RESET_FAVORITE_SAGA_CITY = 'RESET_FAVORITE_SAGA_CITY'