export const FETCH_GEOLOCATION_REQUEST = 'FETCH_GEOLOCATION_REQUEST'
export const FETCH_GEOLOCATION_SUCCESS = 'FETCH_GEOLOCATION_SUCCESS'
export const FETCH_GEOLOCATION_FAILURE = 'FETCH_GEOLOCATION_FAILURE'